apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: api-gateway-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pinklemon122@gmail.com
    privateKeySecretRef:
      name: api-gateway-cluster-issuer-key # <- REQUIRED
    solvers:
      - http01:
          ingress:
            class: nginx
